### PR TITLE
Add deposit agreement to checklist on work save form

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Comment by jcoyne** [comment]
2.0.0?

**Comment by jeremyf** [comment]
@jcoyne Given that `active_deposit_agreement_acceptance` is configurable, can we merge this and have a 2.0.0 task to activate this?

**Comment by mjgiarlo** [comment]
@jeremyf Activate it... like, exposing a FlipFlop feature in the UI? That makes sense to me. Do you mind whipping up an enhancement issue for 2.0.0?

**Comment by mjgiarlo** [comment]
@jcoyne Yeah, 2.0.0. I've added that milestone to make that clear.

**Pull request merged**
