### PR TITLE
DRY up require "spec_helper" lines

### PR DESCRIPTION
**Pull request by atz**
This is done once, for everything in `.rspec`.

### CODE REVIEW

**Comment by jcoyne** [comment]
I think it's odd to move away from the pattern that rspec recommends that we use:

https://github.com/rspec/rspec-rails/blob/2-99-maintenance/lib/generators/rspec/model/templates/model_spec.rb#L1

**Comment by atz** [comment]
How?  That is a trivial throwaway example template, not a "best practice" for our 450+ test files.  Do you have a reference where rspec actually gives a recommendation? with a substantive reason?  

"It was in a generator once" is an argument against modifying anything in the whole stack.  We're already fine using this approach in blacklight, in the literal first example file I looked at:
https://github.com/projectblacklight/blacklight/blob/master/spec/models/bookmark_spec.rb

And elsewhere.  I don't consider this question contentious in the least.

**Comment by jcoyne** [comment]
The example in blacklight also had `require 'spec_helper'` until you made the same global search and replace as you are doing here. https://github.com/projectblacklight/blacklight/commit/99507f033ac1740b56e315cc6458b4e976711d78 This to me just seems like doing work without bringing any real benefit and possibly a little bit of confusion for people who are new and might have got a clue to look for dependencies in a file called `spec_helper.rb`

**Comment by atz** [comment]
OK, I see where RSpec [says](https://github.com/rspec/rspec-rails#upgrade-note):
`Rails specs now need this file required beforehand either at the top of the specific file (recommended) or a common configuration location such as your .rspec file.`

I find the repetition galling and I prefer the alternative they also support.  Their main concern seems to be differentiating `rails_helper` and `spec_helper` on a per-file basis.  I don't see that we have 450+ instances of that concern.  I see zero.

**Comment by atz** [comment]
To be clear, your preferred state is that we leave a trail of 450+ `require` statements that **do nothing**, purely as a breadcrumb trail for newcomers, not just to the project, but to rspec fundamentals overall.  I'm all for hospitality, but redundant executable code feels like the opposite to me.

**Comment by jcoyne** [comment]
Yes, that's my view.  Leave it easy to understand.

**Comment by atz** [comment]
At the point we are writing executable code as an aid to hypothetical newcomers who have apparently **never used rspec**, I think we've left "easy to understand".  Any code that can be functionally replaced with a comment, shouldn't be given some privilege to remain in execution as "explanatory".

**Comment by mjgiarlo** [comment]
I'm good with this change. We do it elsewhere.

**Comment by mjgiarlo** [comment]
Thx, @atz!

**Comment by jrochkind** [comment]
How do the "require" statements do nothing?

Don't they make it possible to run `bundle exec rspec some_particular_spec.rb`?  I do that _all the time_, a bit annoyed you've removed the ability to do that. It's very standard rspec, is it not?

**Comment by mjgiarlo** [comment]
@jrochkind I do that all the time, too, and AFAICT, @atz's change doesn't break that method of invocation. If it does, let us know!

**Comment by dunn** [comment]
> hypothetical newcomers who have apparently never used rspec

FWIW I was such a newcomer; I hadn't used rspec until I started working on Hydra.

**Pull request merged**
