### PR TITLE
Changed after_destroy to before_destroy for cleaning derivatives 

### LINKED ISSUE #762: Ldp::Gone error after deleting a work or files from a work
When I delete a work or file (delete link in dropdown, or delete button), I get an Ldp::Gone error.
Hyrax master branch

Expected behavior
After deleting a work, it should redirect to the dashboard
After deleting a file from a work, it should redirect to the work

Actual behavior
Ldp::Gone error

Steps to reproduce the behavior

1. Create a new work
1. Delete the work (or a file in the work)

Related work
Same [issue](https://github.com/projecthydra-labs/hyku/issues/940) in Hybox

### PR DESCRIPTION
**Pull request by tap87**
Fixes #762 

@projecthydra-labs/hyrax-code-reviewers

### CODE REVIEW

**Comment by jeremyf** [comment]
I'm assuming that the spec fails if you switch the callback to after_destroy? Is that correct?

**Comment by tap87** [comment]
@jeremyf Yes, the spec fails for after_destroy.

**Comment by mjgiarlo** [comment]
Works for me, @tap87. Any further comment on changing the timing of when derivs are destroyed, @projecthydra-labs/hyrax-code-reviewers ?

**Comment by tap87** [comment]
Thanks @jeremyf @mjgiarlo I updated the spec to use hyrax my_works_path instead of the hardcoded value.

**Pull request merged**
