### PR TITLE
Relax template so it points to latest released Hyrax

### PR DESCRIPTION
**Pull request by cjcolvar**
This would be more in line with Blacklight's approach (https://github.com/projectblacklight/blacklight/blob/master/template.demo.rb#L1) and follows the decision made in #492.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@cjcolvar @jcoyne @jeremyf Hrmm, I'm not sure this does follow the decision made in #492. Once v1.0.2 is released, and I am following the instructions in v1.0.1's README (which points at the template in `master`), I will get v1.0.2 installed instead of v1.0.1. Steps 3 and 4 of Hyrax's release management documentation were updated after #492 was closed: https://github.com/samvera-labs/hyrax/wiki/Release-management-process It's too late to make any changes to 1.0.1, but I'd like to be faithful to our release docs in the future (though I understand that mistakes will be made because we're all overburdened and pushing through a lot of work very quickly).

**Comment by jcoyne** [comment]
@mjgiarlo what's the process for changing that?  I'd be in favor of striking 4 and modifying 3 so that they are no longer necessary.  Do we need a review step? Does that belong in a wiki or under version control?

**Comment by mjgiarlo** [comment]
@jcoyne The only approach for "fixing" this in v1.0.1 is to tweak `template.rb` in `1-0-stable` and re-cut the tag. I don't like that idea very much, myself, because it introduces variation (however slight) between the tag and its corresponding release. This is more about how we handle the installation template and README going forward.

As for striking 4 and modifying 3, that's what we discussed in #492, and most folks were onboard with the approach that we currently have documented so I'm not sure why we'd go back on that. (Though your strong preference for the "#1 option" on that issue is clear!) If you feel that steps 3 and 4 are too cumbersome, I'd be happy to help out when it's release time. I'm not sure we need a review step but I'm open to it?

Tagging @samvera-labs/hyrax-code-reviewers for their input here too.

**Comment by jcoyne** [comment]
@mjgiarlo Can you explain how you'd hit that problem that requires this fix?

> is to tweak template.rb in 1-0-stable and re-cut the tag

I imagine that the only use case for the template is:

```
rails _5.0.3_ new my_app -m https://raw.githubusercontent.com/samvera-labs/hyrax/master/template.rb
```
In which case it's retrieving the fixed template from the master branch.

**Comment by mjgiarlo** [comment]
@jcoyne If I follow you, here's what I have in mind. 2.0.0 is cut tomorrow. A person coming over from Sufia 7 wants to install Hyrax 1.0.1. They go to the 1.0.1 README and follow instructions. README says install using the template in `master`. That installs 2.0.0, not 1.0.1.

**Comment by jcoyne** [comment]
If you're coming from something like sufia, you wouldn't use a template, you'd update your existing Gemfile.

**Comment by mjgiarlo** [comment]
`s/coming over from Sufia 7//`, then.

**Comment by hackmastera** [comment]
Just noticing. This looks merged but unresolved.

**Comment by mjgiarlo** [comment]
@hackmastera Here's my take of where things stand: v1.0.1 is already cut, so we can't do much there, but we have a release management document that should help make sure we follow the process for future releases.

**Comment by jcoyne** [comment]
@mjgiarlo I still don't know who would want to come from not the latest version of sufia to an old version of hyrax and use a template to do so.  If you are going to start from scratch (the use case for a template), you'd most certainly want the latest thing to avoid an upgrade in the near future.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> If you are going to start from scratch (the use case for a template), you'd most certainly want the latest thing to avoid an upgrade in the near future.

My experience in the Samvera Community tells me this is often, but not always, true. I'm thinking about Sufia usage patterns around the time of 5 -> 6 -> 7. And the cost of the extra step is super low. I admit this is a "just in case" sort of thing, but the courtesy doesn't put us out very much.

**Pull request merged**
