### PR TITLE
Apply data attributes so page doesn't get reloaded for each tab

### PR DESCRIPTION
**Pull request by jcoyne**
@projecthydra/hyrax-code-reviewers

### CODE REVIEW

**Comment by jpstroop** [comment]
Is @projecthydra/hyrax-code-reviewers a thing yet?

**Comment by escowles** [comment]
@jpstroop It is now — with the same membership as @projecthydra/sufia-code-reviewers

**Comment by jeremyf** [comment]
@mjgiarlo Since you approved, does that mean it's good to merge?

**Comment by mjgiarlo** [comment]
Yessir!

**Comment by jeremyf** [comment]
@mjgiarlo Then you push the button!

**Pull request merged**
