### PR TITLE
Update carrierwave dependency

### PR DESCRIPTION
**Pull request by atz**
Last touched in 2015.  Since then v1.0.0 came out.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:red_circle:

**Comment by atz** [comment]
Can't see how this would be related:
```
1) Hyrax::UsersController#update validates the content type of an avatar
     Failure/Error: UserEditProfileEventJob.perform_later(@user)
     
   (UserEditProfileEventJob (class)).perform_later(#<User id: 1, avatar_file_name: "image.jp2", email: "user379@example.com", orcid: nil, created_at: "2..."r/SXfzBvV/2nKWDrhm+MtP1gx1ygvAvx", arkivo_subscription: nil, zotero_token: nil, zotero_userid: nil>)
           expected: 0 times with any arguments
           received: 1 time with arguments: (#<User id: 1, avatar_file_name: "image.jp2", email: "user379@example.com", orcid: nil, created_at: "2..."r/SXfzBvV/2nKWDrhm+MtP1gx1ygvAvx", arkivo_subscription: nil, zotero_token: nil, zotero_userid: nil>)
 # ./app/controllers/concerns/hyrax/users_controller_behavior.rb:45:in `update'
 # ./spec/controllers/hyrax/users_controller_spec.rb:169:in `block (3 levels) in <top (required)>'
```

If it were a problem with avatar_file_name, that would make sense to me, since an uploader is mounted there.  But this is saying the `perform_later` is never even called.  Weird.

**Comment by mjgiarlo** [comment]
This is related to CarrierWave in that this test is checking to make sure jp2 files are marked as not valid, I believe.

**Comment by mjgiarlo** [comment]
Something with how https://github.com/projecthydra-labs/hyrax/commit/d1e70750c772d83a4c4b904572de51e4bb80ac7c#diff-7e86af7492d1b5ac38d9d07fc396bc46R19 works changed?

**Comment by mjgiarlo** [comment]
@atz yep, seeing the breaking changes listed here: https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md#changed-1

That whitelist method changed names.

**Comment by atz** [comment]
@mjgiarlo thx, that seems like it.

**Pull request merged**
